### ISSUE TITLE
Failed to resolve import "./Stores/user" from "node_modules/svelte-appwrite/src/stores.js"

### ISSUE THREAD

**Issue by lgs** [appwrite/sdk-for-svelte#10]
I got this error trying to implement Authentication via E-Mail like described in [the amazing article here](https://dev.to/torstendittmann/svelte-for-appwrite-4fkg).

```
19:05:49 [vite] Error when evaluating SSR module /node_modules/svelte-appwrite/src/appwrite.js:
TypeError: __vite_ssr_import_0__.default is not a constructor
    at /node_modules/svelte-appwrite/src/appwrite.js:4:8
    at instantiateModule (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:68919:166)
19:05:52 [vite] Internal server error: Failed to resolve import "./Stores/user" from "node_modules/svelte-appwrite/src/stores.js". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/lsoave/SVELTE/svelte-kit-boot/node_modules/svelte-appwrite/src/stores.js
  1  |  import { writable } from "svelte/store";
  2  |  import { UserStore } from "./Stores/user";
     |                             ^
  3  |  import { DocumentsStore } from "./Stores/documents";
  4  |  
      at formatError (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:43464:46)
      at TransformContext.error (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:43460:19)
      at normalizeUrl (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:44974:26)
      at async TransformContext.transform (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:45103:57)
      at async Object.transform (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:43662:30)
      at async transformRequest (/home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:59322:29)
      at async /home/lsoave/SVELTE/svelte-kit-boot/node_modules/vite/dist/node/chunks/dep-0776dd57.js:59444:32
```
The stack I'm using is on Svelte kit actually: 
```
{
	"name": "svelte-kit",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"start": "svelte-kit start"
	},
	"devDependencies": {
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"autoprefixer": "^10.2.5",
		"cssnano": "^4.1.10",
		"postcss": "^8.2.7",
		"postcss-load-config": "^3.0.1",
		"svelte": "^3.29.0",
		"svelte-preprocess": "^4.6.9",
		"tailwindcss": "^2.0.3",
		"vite": "^2.1.0"
	},
	"type": "module",
	"engines": {
		"node": ">= 12.17.0"
	},
	"dependencies": {
		"svelte-appwrite": "^0.2.1-beta"
	}
}
```
I'm not sure it is compatible with your work ... 
any suggestion ?

**Comment by TorstenDittmann** [comment]
Should in theory work with svelte/kit, looks like have casing inconsistencies on the imports!

Fixing them now and will publish a hotfix asap 👍🏻

**Comment by TorstenDittmann** [comment]
Just released `0.2.2-beta` with a fix for that 🚀 

Give it a good minute and should be live 🙂 

Please verify it fixed the error :bow:

**Comment by TorstenDittmann** [comment]
Ah, just realized there might be another thing that needs to be fixed.

Currently the Web SDK - which is used in the Svelte SDK - gets instantiated in the window object. That could potentially be a blocker for svelte/kit right now.

But, there is rescue on the way! I have a pending PR right now which refactors the current Web SDK to support packages for ESM/CJS and UMD. This will make it SSR-ready 👍🏻 

Pending PR: https://github.com/appwrite/sdk-generator/pull/140

PS: I already generated a repo for the refactored SDK [here](https://github.com/TorstenDittmann/appwrite-refactor). Feel free to try it out before everyone else via `npm i TorstenDittmann/appwrite-refactor` 🙂  (temporary repo)

**Comment by lgs** [comment]
Installing 0.2.2-beta I got HTTP error 500:  __vite_ssr_import_0__.default is not a constructor
The I tried to install TorstenDittmann/appwrite-refactor and I got the following (see the [full log here](https://gist.github.com/lgs/0d9d166a6869b70a47f096281d55230d)):
```
lsoave@basenode:~/SVELTE/svelte-kit-boot$ npm i TorstenDittmann/appwrite-refactor
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/lsoave/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path /home/lsoave/.npm/_cacache/tmp/git-clone-1a4d1aa7/node_modules/playwright
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c node install.js
npm ERR! npm ERR! chromium v857950 downloaded to /home/lsoave/.cache/ms-playwright/chromium-857950
npm ERR! npm ERR! firefox v1238 downloaded to /home/lsoave/.cache/ms-playwright/firefox-1238
npm ERR! npm ERR! (node:62138) UnhandledPromiseRejectionWarning: Error: Failed to download webkit, caused by
npm ERR! npm ERR! Error: read ECONNRESET
npm ERR! npm ERR!     at TLSWrap.onStreamRead (internal/stream_base_commons.js:208:20)
npm ERR! npm ERR!     at /home/lsoave/.npm/_cacache/tmp/git-clone-1a4d1aa7/node_modules/playwright/lib/install/installer.js:130:19
npm ERR! npm ERR!     at async validateCache (/home/lsoave/.npm/_cacache/tmp/git-clone-1a4d1aa7/node_modules/playwright/lib/install/installer.js:129:9)
npm ERR! npm ERR!     at async installBrowsersWithProgressBar (/home/lsoave/.npm/_cacache/tmp/git-clone-1a4d1aa7/node_modules/playwright/lib/install/installer.js:80:9)
npm ERR! npm ERR! (node:62138) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
npm ERR! npm ERR! (node:62138) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/lsoave/.npm/_logs/2021-03-29T18_50_32_169Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lsoave/.npm/_logs/2021-03-29T18_50_32_296Z-debug.log
```

**Comment by TorstenDittmann** [comment]
Okay, this is indeed the error I suspected. Sadly you have to wait until the refactored Web SDK is released before you can use svelte/kit. 

Fixed the `TorstenDittmann/appwrite-refactor` repo now by removing unnecessary dependencies 👍🏻 

But fyi, this is not a Svelte SDK but the normal Web SDK 👍🏻

**Comment by TorstenDittmann** [comment]
Gonna try and wrap up the new SDK tomorrow and push a fix as soon as we can 🙂
