### ISSUE TITLE
Support SvelteKit and appwrite 0.3.0-beta

### ISSUE THREAD

**Issue by abovethewater** [appwrite/sdk-for-svelte#17]
The latest version in npm is tied to appwrite ^0.2.3-beta

This does not seem to work with sveltekit out of the box:

`__vite_ssr_import_0__.default is not a constructor`

Installing direct from master gets further:

```
ReferenceError: require is not defined
    at /node_modules/.pnpm/cross-fetch@3.1.4/node_modules/cross-fetch/dist/node-ponyfill.js?v=5ad71818:1:19
    at instantiateModule (/Users/jmathews/leavenoprints/leavenoprints-v1/node_modules/.pnpm/vite@2.4.1/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:72639:166)
10:04:51 [vite] Error when evaluating SSR module /node_modules/.pnpm/isomorphic-form-data@2.0.0/node_modules/isomorphic-form-data/lib/index.js?v=5ad71818:
ReferenceError: module is not defined
    at /node_modules/.pnpm/isomorphic-form-data@2.0.0/node_modules/isomorphic-form-data/lib/index.js?v=5ad71818:1:19
    at instantiateModule (/Users/jmathews/leavenoprints/leavenoprints-v1/node_modules/.pnpm/vite@2.4.1/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:72639:166)
10:04:51 [vite] Error when evaluating SSR module /node_modules/.pnpm/cross-fetch@3.1.4/node_modules/cross-fetch/dist/node-ponyfill.js?v=5ad71818:
ReferenceError: require is not defined
    at /node_modules/.pnpm/cross-fetch@3.1.4/node_modules/cross-fetch/dist/node-ponyfill.js?v=5ad71818:1:19
    at instantiateModule (/Users/jmathews/leavenoprints/leavenoprints-v1/node_modules/.pnpm/vite@2.4.1/node_modules/vite/dist/node/chunks/dep-cc49d7be.js:72639:166)
```

Adding the appwrite dependency explicitly, gets further, now compiles without issues, but the following error is seen in console:

`Uncaught (in promise) SyntaxError: import not found: fetch`

Adding appwrite to optimizeDeps fixes this:

```
  kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    target: '#svelte',
    adapter: adapter(),
    vite: {
      optimizeDeps: {
        include: ['appwrite'],
      },
    }
  }
```

I am using pnpm if that makes a difference.
Appwrite 3.2.0
SvelteKit v1.0.0-next.123

Thanks

**Comment by TorstenDittmann** [comment]
Yes, this library doesn't support svelte kit yet. But our normal Web SDK does Support SvelteKit/SSR.

**Comment by YugoCode** [comment]
Hey @TorstenDittmann, first of all **thank you very much for this SDK!** ❤️ As a developer who just recently fell in love with svelte(kit) and Appwrite I couldn't have dreamt for something better! This SDK allows us to start right away, removing most of the complexity!

Svelte(kit) is getting more and more popular and I think this SDK would be a key factor for many devs to go with Appwrite instead of Supabase or other solutions since it makes everything so easy to use! Just recently on reddit there was a big discussion on [authentication backends used by sveltekit devs](https://www.reddit.com/r/sveltejs/comments/vos2ul/most_recommended_authentication_backend_for/) - most people use Supabase, Appwrite was just mentioned once. But this shouldn't be the case! Supabase had to come up with [auth-helpers](https://github.com/supabase-community/auth-helpers), because it's just to complicated for beginners to implement authentication! (btw their sveltekit helpers are still not fully functional). 

Unfortunately, it seems that sveltekit and the latest Appwrite version (15.1) are not supported by this SDK 🥺 Could you or @eldadfux **please tell the community your plans in adding support for sveltekit + Appwrite 15.1** and basically continuing maintenance for this SDK?

PS. Someone already started a fork and adding support, so maybe this helps you for updating the SDK: [metawrite](https://github.com/koodeau/metawrite)

**Comment by EVDOG4LIFE** [comment]
Due to age, and given that we are quite a few versions ahead - is this still needed?
